name: ace5pro_kernel_6.6‰∏äÊ∏∏ÂêàÂπ∂

on:
  workflow_dispatch:
    inputs:
      CPU_ARCH:
        description: "ÁõÆÊ†áCPUÊû∂ÊûÑÂàÜÊîØÔºå‰æãÂ¶Ç sm8750 (ÈªòËÆ§: sm8750)"
        required: true
        default: 'sm8750'
      DEVICE_CONFIG:
        description: "ËÆæÂ§áÈÖçÁΩÆÊñá‰ª∂ÂêçÁß∞Ôºå‰æãÂ¶Ç oneplus_ace5_pro (ÈªòËÆ§: oneplus_ace5_pro)"
        required: true
        default: 'oneplus_ace5_pro'
      ANDROID_TARGET_VERSION:
        description: "ÁõÆÊ†áAndroidÁâàÊú¨Ôºå‰æãÂ¶Ç android15 (ÈªòËÆ§: android15)"
        required: true
        default: 'android15'
      KERNEL_BASE_VERSION:
        description: "ÂÜÖÊ†∏Âü∫Á°ÄÁâàÊú¨Ôºå‰æãÂ¶Ç 6.6 (ÈªòËÆ§: 6.6)"
        required: true
        default: '6.6'
      CUSTOM_KERNEL_NAME_TAG:
        description: "Ëá™ÂÆö‰πâÂÜÖÊ†∏ÂêçÁß∞Ê†áËØÜÔºåÂ∞ÜÈôÑÂä†Âà∞ÂÜÖÊ†∏ÁâàÊú¨Âè∑Âêé (‰æãÂ¶Ç: -android15-8-g013ec21bba94-abogki383916444)"
        required: true
        default: '-android15-8-g013ec21bba94-abogki383916444-4k'
      LOCAL_VERSION_SUFFIX:
        description: 'ÂÜÖÊ†∏ÁâàÊú¨ÂêéÁºÄÔºàÂ¶Ç-v8ÔºåÈªòËÆ§Ôºö-4kÔºâ'
        required: false
        default: ''
        type: string
      REMOVE_DEFAULT_4K_SUFFIX:
        description: 'ÊòØÂê¶Âà†Èô§ÈªòËÆ§ÁöÑ -4k ÂêéÁºÄÔºüÔºàÂãæÈÄâÂàôÂà†Èô§Ôºâ'
        required: false
        default: true
        type: boolean
      BUILD_TIMESTAMP:
        description: 'ÂÜÖÊ†∏ÊûÑÂª∫Êó∂Èó¥ (UTCÊ†ºÂºèÔºå‰æãÂ¶Ç "Tue Dec 17 23:36:49 UTC 2024")'
        required: false
        default: 'Tue Dec 17 23:36:49 UTC 2024'
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_HARDLINK: "true"
      TOKEN: ${{ secrets.TOKEN }}
    
    steps:
      - name: 1.1 ÊúÄÂ§ßÂåñÊûÑÂª∫Á©∫Èó¥
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 8192
          temp-reserve-mb: 2048
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          
      - name: 1.2 ÈÖçÁΩÆGitÁî®Êà∑‰ø°ÊÅØ
        run: |
         git config --global user.name "github-actions[bot]"
         git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: 1.3 Ê£ÄÂá∫Â∑•‰ΩúÊµÅ‰ªìÂ∫ì‰ª£Á†Å  
        uses: actions/checkout@v4  

      - name: 1.4 ÂÆâË£ÖÊûÑÂª∫Ê†∏ÂøÉ‰æùËµñ  
        run: |  
         sudo apt-get update  
         sudo apt-get install -y --no-install-recommends python3 git curl ccache libelf-dev build-essential

      - name: 2.1 ÊÅ¢Â§ç ccache ÁºìÂ≠ò
        uses: actions/cache@v4
        with:
         path: /home/runner/.ccache
         key: ${{ runner.os }}-${{ github.repository }}-${{ github.ref_name }}-v2_ksun
         restore-keys: |
          ${{ runner.os }}-${{ github.repository }}-${{ github.ref_name }}-ccache-
          ${{ runner.os }}-${{ github.repository }}-ccache-
          ${{ runner.os }}-ccache-
    
      - name: 2.2 ÈÖçÁΩÆ ccache
        run: |  
         echo "CCACHE_DIR=/home/runner/.ccache" >> $GITHUB_ENV  
         echo "CCACHE_MAXSIZE=8G" >> $GITHUB_ENV  
         echo "CCACHE_COMPILERCHECK=%compiler% -dumpmachine; %compiler% -dumpversion" >> $GITHUB_ENV  
         echo "CCACHE_NOHASHDIR=true" >> $GITHUB_ENV  
         echo "CCACHE_HARDLINK=true" >> $GITHUB_ENV  
         echo "CCACHE_BASEDIR=${{ github.workspace }}" >> $GITHUB_ENV  
         echo "CCACHE_LOGFILE=${{ github.workspace }}/ccache.log" >> $GITHUB_ENV  
         echo "/usr/lib/ccache" >> $GITHUB_PATH  
         
      - name: Show ccache stats
        run: |
         ccache -s || true
         
      - name: 3.1 ÂÆâË£Ö repo Â∑•ÂÖ∑
        run: |
         curl -sSL https://storage.googleapis.com/git-repo-downloads/repo > ~/repo
         chmod a+x ~/repo
         sudo mv ~/repo /usr/local/bin/repo

      - name: 3.2 ÂàùÂßãÂåñÂπ∂ÂêåÊ≠•ÂÜÖÊ†∏Ê∫êÁ†Å
        run: |
         mkdir -p kernel_workspace && cd kernel_workspace
         repo init -u https://github.com/3620603660/kernel_manifest.git -b refs/heads/oneplus/${{ github.event.inputs.CPU_ARCH }} -m ${{ github.event.inputs.DEVICE_CONFIG }}.xml --depth=1
         repo sync -c -j$(nproc) --no-tags --no-clone-bundle
         rm -f kernel_platform/common/android/abi_gki_protected_exports_* || echo "No protected exports to remove."
         rm -f kernel_platform/msm-kernel/android/abi_gki_protected_exports_* || echo "No protected exports to remove."
         
      - name: 4.1 ËÆæÁΩÆ KernelSU Next
        run: |
          cd kernel_workspace/kernel_platform
          curl -LSs "https://raw.githubusercontent.com/KernelSU-Next/KernelSU-Next/next/kernel/setup.sh" | bash -s next
          cd KernelSU-Next
          KSU_VERSION=$(expr $(/usr/bin/git rev-list --count HEAD) "+" 10200)
          echo "KSUVER=$KSU_VERSION" >> $GITHUB_ENV
          sed -i "s/DKSU_VERSION=11998/DKSU_VERSION=${KSU_VERSION}/" kernel/Makefile

      - name: 5.1 ËÆæÁΩÆ SUSFS & Â∫îÁî®Ë°•‰∏Å
        run: |
         set -e
         cd kernel_workspace
         git clone --depth=1 https://gitlab.com/simonpunk/susfs4ksu.git -b gki-${{ inputs.ANDROID_TARGET_VERSION }}-${{ inputs.KERNEL_BASE_VERSION }}
         git clone --depth=1 https://github.com/SukiSU-Ultra/SukiSU_patch.git
         git clone --depth=1 https://$TOKEN@github.com/3620603660/boot.git
         git clone --depth=1 https://github.com/WildPlusKernel/kernel_patches.git
         git clone --depth=1 https://github.com/3620603660/GKI_KernelSU_SUSFS.git zzh_patch
         
         cd kernel_platform
         cp -f ../susfs4ksu/kernel_patches/50_add_susfs_in_gki-${{ github.event.inputs.ANDROID_TARGET_VERSION }}-${{ github.event.inputs.KERNEL_BASE_VERSION }}.patch ./common/ || true
         cp -f ../susfs4ksu/kernel_patches/KernelSU/10_enable_susfs_for_ksu.patch ./KernelSU-Next/ || true
         cp -f ../zzh_patch/next-patch/* ./KernelSU-Next/ || true
         cp -f ../susfs4ksu/kernel_patches/fs/* ./common/fs/ || true
         cp -f ../susfs4ksu/kernel_patches/include/linux/* ./common/include/linux/ || true
         cp -f ../boot/1.patch ./common/ || true
         
         cd ./KernelSU-Next
         patch -p1 --forward --fuzz=3 < 10_enable_susfs_for_ksu.patch || true
         patch -p1 --fuzz=3 --forward < apk_sign.patch || true
         patch -p1 --fuzz=3 --forward < core_hook.patch || true
         patch -p1 --fuzz=3 --forward < ksud.patch || true
         patch -p1 --fuzz=3 --forward < selinux.patch || true
         patch -p1 --fuzz=3 --forward < rules.c.patch || true
         patch -p1 --fuzz=3 --forward < sucompat.c.patch || true
         patch -p1 --fuzz=3 --forward < kernel_compat.c.patch || true
         patch -p1 --fuzz=3 --forward < min_scope_syscall_hooks_v1.4.patch || true
         cd ../
         
         cd ./common/
         patch -p1 < 50_add_susfs_in_gki-${{ github.event.inputs.ANDROID_TARGET_VERSION }}-${{ github.event.inputs.KERNEL_BASE_VERSION }}.patch || true
         cp -f ../../kernel_patches/69_hide_stuff.patch ./
         cp -f ../../kernel_patches/next/scope_min_manual_hooks_v1.4.patch ./
         patch -p1 -F 3 < scope_min_manual_hooks_v1.4.patch || true
         patch -p1 -F 3 < 69_hide_stuff.patch || true
         patch -s -p1 -F 3 < 1.patch || true
         echo "‚úÖ SUSFS Âíå scope_min_manual_hooks_v1.4 patch Â∫îÁî®ÂÆåÊàê"

         sed -i '/^static inline int ksu_access_ok/,/^}/ s/^/\/\//' drivers/kernelsu/kernel_compat.c || true
         
      - name: 6.1 Ê∑ªÂä† SUSFS ÂèäÊÄßËÉΩ‰ºòÂåñÈÖçÁΩÆ
        run: |
          cd kernel_workspace/kernel_platform
          
          echo "CONFIG_KSU=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_KPROBES_HOOK=n" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_HAS_MAGIC_MOUNT=y" >> ./common/arch/arm64/configs/gki_defconfig
          
          echo "CONFIG_KSU_SUSFS_SUS_PATH=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SUS_MOUNT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_KSU_DEFAULT_MOUNT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_BIND_MOUNT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SUS_KSTAT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SUS_OVERLAYFS=n" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_TRY_UMOUNT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_AUTO_ADD_TRY_UMOUNT_FOR_BIND_MOUNT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SPOOF_UNAME=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_ENABLE_LOG=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_HIDE_KSU_SUSFS_SYMBOLS=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SPOOF_CMDLINE_OR_BOOTCONFIG=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_OPEN_REDIRECT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SUS_SU=n" >> ./common/arch/arm64/configs/gki_defconfig
          
          echo "CONFIG_LTO_CLANG=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_LTO_CLANG_THIN=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_LTO_POLLY=y" >> ./common/arch/arm64/configs/gki_defconfig

          echo "CONFIG_CRYPTO_LZ4HC=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_CRYPTO_LZ4KD=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_CRYPTO_ZSTD=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_CRYPTO_LZ4=y" >> ./common/arch/arm64/configs/gki_defconfig

          echo "CONFIG_F2FS_FS_LZ4=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_F2FS_FS_LZ4HC=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_F2FS_FS_ZSTD=y" >> ./common/arch/arm64/configs/gki_defconfig

          # ========================================
          # È´òÁ∫ßË∞ÉÂ∫¶Âô®ÁâπÊÄß
          # ========================================
          echo "CONFIG_SCHED_CORE=y" >> ./common/arch/arm64/configs/gki_defconfig         # ÂêØÁî®Ê†∏ÂøÉË∞ÉÂ∫¶
          echo "CONFIG_SCHED_MC=y" >> ./common/arch/arm64/configs/gki_defconfig           # ÂêØÁî®Â§öÊ†∏Ë∞ÉÂ∫¶
          echo "CONFIG_UCLAMP_TASK=y" >> ./common/arch/arm64/configs/gki_defconfig        # ÂêØÁî®‰ªªÂä°Âà©Áî®ÁéáÈôêÂà∂
          echo "CONFIG_UCLAMP_MIN_TUNABLE=y" >> ./common/arch/arm64/configs/gki_defconfig # ÂêØÁî®ÊúÄÂ∞èÂà©Áî®ÁéáË∞ÉËäÇ
          echo "CONFIG_UCLAMP_MAX_TUNABLE=y" >> ./common/arch/arm64/configs/gki_defconfig # ÂêØÁî®ÊúÄÂ§ßÂà©Áî®ÁéáË∞ÉËäÇ
          echo "CONFIG_SCHED_HRTICK=y" >> ./common/arch/arm64/configs/gki_defconfig       # ÂêØÁî®È´òÂàÜËæ®ÁéáÊó∂ÈíüÔºåÊèêÂçáË∞ÉÂ∫¶Á≤æÂ∫¶
          echo "CONFIG_CPU_IDLE_GOV_LADDER=y" >> ./common/arch/arm64/configs/gki_defconfig # ÂêØÁî®Èò∂Ê¢ØÂºèÁ©∫Èó≤Áä∂ÊÄÅÁÆ°ÁêÜÔºå‰ºòÂåñÂäüËÄó
          # Á°Æ‰øùEEVDFË∞ÉÂ∫¶Âô®ÂêØÁî® (Linux 6.6.30ÈªòËÆ§Ôºå‰ΩÜ‰ªçÈúÄÁ°ÆËÆ§)
          echo "CONFIG_SCHED_EEVDF=y" >> ./common/arch/arm64/configs/gki_defconfig
          # Energy Aware Scheduling (EAS) ‰ºòÂåñ
          echo "CONFIG_SCHED_EAS=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_CPU_FREQ_GOV_SCHEDUTIL=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_CPU_FREQ_GOV_PERFORMANCE=n" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_CPU_FREQ_GOV_POWERSAVE=n" >> ./common/arch/arm64/configs/gki_defconfig

          # Cgroup v2 Ë∞ÉÂ∫¶Âô®Êé•Âè£ (Â¶ÇÊûúÈúÄË¶ÅÊõ¥ÁªÜÁ≤íÂ∫¶ËµÑÊ∫êÊéßÂà∂)
          echo "CONFIG_CGROUP_SCHED=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_FAIR_GROUP_SCHED=y" >> ./common/arch/arm64/configs/gki_defconfig
          
          # ========================================
          # ÂÜÖÂ≠òÁÆ°ÁêÜ‰ºòÂåñ
          # ========================================
          echo "CONFIG_LRU_GEN=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_TRANSPARENT_HUGEPAGE=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_TRANSPARENT_HUGEPAGE_MADVISE=y" >> ./common/arch/arm64/configs/gki_defconfig
          
          # ========================================
          # ÁΩëÁªúÊÄßËÉΩ‰ºòÂåñ (BBR + Cake + ECN)
          # ========================================
          echo "CONFIG_NET_SCHED=y" >> ./common/arch/arm64/configs/gki_defconfig
          # Êñ∞Â¢û‰∏ãÈù¢ËøôË°åÔºåÂêØÁî® Cake Ë∞ÉÂ∫¶Âô®
          echo "CONFIG_NET_SCH_CAKE=y" >> ./common/arch/arm64/configs/gki_defconfig      # ÂêØÁî®CakeÈòüÂàóÁÆ°ÁêÜÁÆóÊ≥ï
          echo "CONFIG_NET_SCH_FQ=y" >> ./common/arch/arm64/configs/gki_defconfig
          # Êñ∞Â¢û‰∏ãÈù¢ËøôË°åÔºåÁ°Æ‰øù ECN ÂºÄÂêØ
          echo "CONFIG_INET_ECN=y" >> ./common/arch/arm64/configs/gki_defconfig          # Á°Æ‰øùÂêØÁî®ÊòæÂºèÊã•Â°ûÈÄöÁü•
          # Êñ∞Â¢û‰∏ãÈù¢ËøôË°åÔºåÂ∞Ü Cake ËÆæ‰∏∫ÈªòËÆ§ÁΩëÁªúË∞ÉÂ∫¶Âô®
          echo "CONFIG_DEFAULT_NET_SCH=\"cake\"" >> ./common/arch/arm64/configs/gki_defconfig # ËÆæÁΩÆCake‰∏∫ÈªòËÆ§ÁΩëÁªúË∞ÉÂ∫¶Âô®
          # Êñ∞Â¢û‰∏ãÈù¢Âá†Ë°åÔºå‰ΩøÁî® sed ÂëΩ‰ª§ÁßªÈô§ÂÖ∂‰ªñ‰∏çÂÜçÈúÄË¶ÅÁöÑ TCP Êã•Â°ûÁÆóÊ≥ïÔºå‰ª•ÂáèÂ∞èÂÜÖÊ†∏‰ΩìÁßØ
          echo "CONFIG_TCP_CONG_BIC=n" >> ./common/arch/arm64/configs/gki_defconfig # ÂêØÁî® BIC TCP Êã•Â°ûÊéßÂà∂ÁÆóÊ≥ï
          echo "CONFIG_TCP_CONG_CUBIC=n" >> ./common/arch/arm64/configs/gki_defconfig # ÂêØÁî® CUBIC TCP Êã•Â°ûÊéßÂà∂ÁÆóÊ≥ï
          echo "CONFIG_TCP_CONG_WESTWOOD=n" >> ./common/arch/arm64/configs/gki_defconfig # ÂêØÁî® WESTWOOD TCP Êã•Â°ûÊéßÂà∂ÁÆóÊ≥ï
          echo "CONFIG_TCP_CONG_HTCP=n" >> ./common/arch/arm64/configs/gki_defconfig # ÂêØÁî® HTCP TCP Êã•Â°ûÊéßÂà∂ÁÆóÊ≥ï

          # ========================================
          # ÂäüËÄóÁÆ°ÁêÜÂíåÁîµÊ∫ê‰ºòÂåñ
          # ========================================
          echo "CONFIG_CPU_FREQ=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_CPU_FREQ_STAT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_CPU_IDLE=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_DRM_GPU_SCHED=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_PM_WAKELOCKS=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_PM_WAKELOCKS_GC=y" >> ./common/arch/arm64/configs/gki_defconfig

          sed -i 's/check_defconfig//' ./common/build.config.gki
          git add -A && git commit -a -m "BUILD Kernel"

      - name: 7.1 ‰øÆÊîπÂÜÖÊ†∏ÁâàÊú¨ÊòæÁ§∫ÂêçÁß∞
        run: |
         cd kernel_workspace/kernel_platform
         sed -i '186s|echo ".*"|echo "${KERNELVERSION}${scm_version}${config_localversion}"|' common/scripts/setlocalversion
         sed -i "s/\${scm_version}/${{ github.event.inputs.CUSTOM_KERNEL_NAME_TAG }}/g" ./common/scripts/setlocalversion
         
      - name: 7.2 ËÆæÁΩÆ CONFIG_LOCALVERSION
        run: |
         cd kernel_workspace/kernel_platform
         echo 'CONFIG_LOCALVERSION="${{ github.event.inputs.LOCAL_VERSION_SUFFIX }}"' >> ./common/arch/arm64/configs/gki_defconfig

      - name: 7.3 Âà†Èô§ CONFIG_LOCALVERSION ‰∏≠ÁöÑ -4k ÂêéÁºÄÔºàÂ¶ÇÊûúÂãæÈÄâÔºâ
        if: ${{ fromJSON(github.event.inputs.REMOVE_DEFAULT_4K_SUFFIX) }}
        run: |
         cd kernel_workspace/kernel_platform
         sed -i 's/-4k//' ./common/arch/arm64/configs/gki_defconfig
    
      - name: ÊãâÂèñafdo
        run: |
          cd kernel_workspace/kernel_platform/
          git clone https://github.com/PxxPei/afdo.git

      - name: 9.1 ËÆæÁΩÆÊûÑÂª∫Êó∂Èó¥Êà≥
        run: |         
         export SOURCE_DATE_EPOCH=$(date -d "${{ github.event.inputs.BUILD_TIMESTAMP }}" +%s)
         echo "SOURCE_DATE_EPOCH=$SOURCE_DATE_EPOCH" >> $GITHUB_ENV

      - name: üì¶ Install and Setup Clang 19.0.0 compiler environment
        run: |
         mkdir -p clang19
         cd clang19
         wget https://github.com/ZyCromerZ/Clang/releases/download/19.0.0git-20240723-release/Clang-19.0.0git-20240723.tar.gz
         tar -zvxf Clang-19.0.0git-20240723.tar.gz
         
      - name: 10.1 ÁºñËØëÂÜÖÊ†∏
        run: |
          export CLANG_PATH="${{ github.workspace }}/clang19/bin"
          export PATH="${CLANG_PATH}:${PATH}"
          export PATH="/usr/lib/ccache:${PATH}"
          
          export KERNEL_TIME="${{ github.event.inputs.BUILD_TIMESTAMP }}"
          export KBUILD_BUILD_TIMESTAMP="$KERNEL_TIME"
          export SOURCE_DATE_EPOCH=$(date -d "$KERNEL_TIME" +%s )
          
          export AFDO_PROFILE="${{ github.workspace }}/kernel_workspace/kernel_platform/afdo/kernel.afdo"
          if [ ! -f "$AFDO_PROFILE" ]; then
              echo "Error: AFDO profile not found at $AFDO_PROFILE"
          exit 1
          fi
          
          echo "KERNEL_TIME = $KERNEL_TIME"
          echo "SOURCE_DATE_EPOCH = $SOURCE_DATE_EPOCH"
          echo "Using KCFLAGS: -Wno-error -fauto-profile=$AFDO_PROFILE"
          
          export CC="ccache clang"
          export KCFLAGS="-Wno-error -fauto-profile=$AFDO_PROFILE"
          export MAKE_ARGS="LLVM=1 ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- CC=clang \
          RUSTC=../../prebuilts/rust/linux-x86/1.73.0b/bin/rustc \
          PAHOLE=../../prebuilts/kernel-build-tools/linux-x86/bin/pahole \
          LD=ld.lld HOSTLD=ld.lld O=out SOURCE_DATE_EPOCH=${SOURCE_DATE_EPOCH}"
          
          cd kernel_workspace/kernel_platform/common
          rm -rf out
          
          make $MAKE_ARGS gki_defconfig

          make -j$(nproc) $MAKE_ARGS all
          export KBUILD_CFLAGS="-O2 -flto=thin"

          if [ ! -f "out/arch/arm64/boot/Image" ]; then
            echo "‚ùå ÂÜÖÊ†∏ÁºñËØëÂ§±Ë¥•ÔºåÊú™ÊâæÂà∞ Image Êñá‰ª∂ÔºÅ"
            exit 1
          fi
          
          mkdir -p ../dist
          cp out/arch/arm64/boot/Image ../dist/
          echo "‚úÖ ÂÜÖÊ†∏ÁºñËØëÊàêÂäüÔºÅ‰∫ßÁâ©Â∑≤Â§çÂà∂Âà∞ dist ÁõÆÂΩï„ÄÇ"
          
      - name: 10.2 È™åËØÅÂÜÖÊ†∏ÊûÑÂª∫Êó∂Èó¥
        run: |
         strings kernel_workspace/kernel_platform/common/out/vmlinux | grep "UTC"

      - name: 11.1 ÂáÜÂ§á AnyKernel3 Âà∑Êú∫ÂåÖ
        run: |
          cd kernel_workspace/kernel_platform/dist
          git clone https://github.com/3620603660/AnyKernel3.git AnyKernel3 --depth=1
          rm -rf AnyKernel3/.git
          rm -f AnyKernel3/push.sh
          cp Image AnyKernel3/

      - name: 11.2 ‰∏ä‰º†ÁºñËØë‰∫ßÁâ©Âà∞ Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: AnyKernel3_${{ github.event.inputs.DEVICE_CONFIG }}_${{ env.KSUVER }}
          path: kernel_workspace/kernel_platform/dist/AnyKernel3/*
